#!/usr/bin/env bash

function set_all_links(){

directory="$HOME/.dotfiles/settings"

for entry in "$directory"/* "$directory"/.[!.]*; do
    name="${entry/\/home\/lucas\/.dotfiles\/settings/}"
    create_link "$entry" "$name"
done
    echo "Link created"
}


function create_link(){
    main_setting="$1"
    sync_setting="$HOME$2"
    
    # TODO: fix the config when doing nvim and config
    if [[ -d $main_setting ]]; then
        # Is a dir
        ln -nsf "$main_setting" "$sync_setting"
    elif [[ -f $main_setting ]]; then
        ln -sf "$main_setting" "$sync_setting"
    else
        echo "$main_setting is not valid"
        exit 1
    fi

    echo "$main_setting" "$sync_setting" linked
}

echo "Linking files"
set_all_links
