#!/usr/bin/env bash

sudo apt -y install fonts-powerline curl wget zsh tmux fzf build-essential ripgrep xclip

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
echo "The tmux package manager it's installed. You will have to enter into tmux and run prefix+I to install the other packages"

#curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#. "$HOME/.cargo/env"
#cargo install cargo-cache
#cargo install cargo-watch

. "$HOME/.dotfiles/scripts/installation/neovimSetup"
. "$HOME/.dotfiles/scripts/installation/createLinks"

echo "Changing the shell"
chsh -s /usr/bin/zsh
echo "Shell changed to zsh"

. "$HOME/.dotfiles/scripts/installation/downloadFonts"

echo "Installing OMZ"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
