#!/usr/bin/env bash

echo "Setting up neovim"
local_bin="$HOME/.local/bin" 

if [[ -d "$local_bin" ]]; then
    echo "Directory exists"
else
    mkdir "$local_bin"
fi

cd $local_bin 

if [[ -f "$local_bin/nvim.appimage" ]]; then
    echo "Nvim installed"
else
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x nvim.appimage
    ./nvim.appimage ./nvim.appimage --appimage-extract
    sudo ln -s "$local_bin"/squashfs-root/AppRun /usr/bin/nvim
fi
